[package]
name = "silo-reports"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
pulldown-cmark.workspace = true
quickjs-rusty.workspace = true
serde.workspace = true
serde_json.workspace = true
silo-core = { path = "../silo-core" }
silo-db = { path = "../silo-db" }
silo-schema = { path = "../silo-schema" }
url.workspace = true
