/**
 * Generated by tsnapi — public API snapshot of `silo`
 */
// #region Variables
export declare const app: Partial<import("cmd-ts/dist/cjs/argparser.js").Register> & {
  parse(context: import("cmd-ts/dist/cjs/argparser.js").ParseContext): Promise<import("cmd-ts/dist/cjs/argparser.js").ParsingResult<{
    command: "status";
    args: {};
  } | {
    command: "database";
    args: {
      command: "list";
      args: {};
    };
  } | {
    command: "template";
    args: {
      command: "list";
      args: {};
    } | {
      command: "show";
      args: {
        name: string;
      };
    };
  } | {
    command: "schema";
    args: {
      command: "show";
      args: {};
    } | {
      command: "export";
      args: {};
    } | {
      command: "ddl";
      args: {};
    } | {
      command: "instantiate";
      args: {
        template: string;
      };
    };
  } | {
    command: "table";
    args: {
      command: "list";
      args: {};
    } | {
      command: "show";
      args: {
        table: string;
      };
    } | {
      command: "create";
      args: {
        file: string | undefined;
      };
    } | {
      command: "alter";
      args: {
        table: string;
        file: string | undefined;
      };
    } | {
      command: "drop";
      args: {
        table: string;
      };
    };
  } | {
    command: "row";
    args: {
      command: "list";
      args: {
        table: string;
        limit: number;
        offset: number;
      };
    } | {
      command: "add";
      args: {
        table: string;
        file: string | undefined;
      };
    } | {
      command: "get";
      args: {
        table: string;
        key: string;
      };
    } | {
      command: "update";
      args: {
        table: string;
        key: string;
        file: string | undefined;
      };
    } | {
      command: "delete";
      args: {
        table: string;
        key: string;
      };
    } | {
      command: "upsert";
      args: {
        table: string;
        file: string | undefined;
      };
    };
  } | {
    command: "sql";
    args: {
      query: string | undefined;
    };
  }>>;
} & import("cmd-ts/dist/cjs/helpdoc.js").Named & Partial<import("cmd-ts/dist/cjs/helpdoc.js").Descriptive & import("cmd-ts/dist/cjs/helpdoc.js").Versioned> & import("cmd-ts/dist/cjs/helpdoc.js").PrintHelp & Partial<import("cmd-ts/dist/cjs/helpdoc.js").Versioned> & import("cmd-ts/dist/cjs/argparser.js").Register & import("cmd-ts/dist/cjs/runner.js").Handling<{
  command: "status";
  args: {};
} | {
  command: "database";
  args: {
    command: "list";
    args: {};
  };
} | {
  command: "template";
  args: {
    command: "list";
    args: {};
  } | {
    command: "show";
    args: {
      name: string;
    };
  };
} | {
  command: "schema";
  args: {
    command: "show";
    args: {};
  } | {
    command: "export";
    args: {};
  } | {
    command: "ddl";
    args: {};
  } | {
    command: "instantiate";
    args: {
      template: string;
    };
  };
} | {
  command: "table";
  args: {
    command: "list";
    args: {};
  } | {
    command: "show";
    args: {
      table: string;
    };
  } | {
    command: "create";
    args: {
      file: string | undefined;
    };
  } | {
    command: "alter";
    args: {
      table: string;
      file: string | undefined;
    };
  } | {
    command: "drop";
    args: {
      table: string;
    };
  };
} | {
  command: "row";
  args: {
    command: "list";
    args: {
      table: string;
      limit: number;
      offset: number;
    };
  } | {
    command: "add";
    args: {
      table: string;
      file: string | undefined;
    };
  } | {
    command: "get";
    args: {
      table: string;
      key: string;
    };
  } | {
    command: "update";
    args: {
      table: string;
      key: string;
      file: string | undefined;
    };
  } | {
    command: "delete";
    args: {
      table: string;
      key: string;
    };
  } | {
    command: "upsert";
    args: {
      table: string;
      file: string | undefined;
    };
  };
} | {
  command: "sql";
  args: {
    query: string | undefined;
  };
}, {
  command: "status";
  value: Promise<void>;
} | {
  command: "database";
  value: {
    command: "list";
    value: Promise<void>;
  };
} | {
  command: "template";
  value: {
    command: "list";
    value: Promise<void>;
  } | {
    command: "show";
    value: Promise<void>;
  };
} | {
  command: "schema";
  value: {
    command: "show";
    value: Promise<void>;
  } | {
    command: "export";
    value: Promise<void>;
  } | {
    command: "ddl";
    value: Promise<void>;
  } | {
    command: "instantiate";
    value: Promise<void>;
  };
} | {
  command: "table";
  value: {
    command: "list";
    value: Promise<void>;
  } | {
    command: "show";
    value: Promise<void>;
  } | {
    command: "create";
    value: Promise<void>;
  } | {
    command: "alter";
    value: Promise<void>;
  } | {
    command: "drop";
    value: Promise<void>;
  };
} | {
  command: "row";
  value: {
    command: "list";
    value: Promise<void>;
  } | {
    command: "add";
    value: Promise<void>;
  } | {
    command: "get";
    value: Promise<void>;
  } | {
    command: "update";
    value: Promise<void>;
  } | {
    command: "delete";
    value: Promise<void>;
  } | {
    command: "upsert";
    value: Promise<void>;
  };
} | {
  command: "sql";
  value: Promise<void>;
}> & {
  run(context: import("cmd-ts/dist/cjs/argparser.js").ParseContext): Promise<import("cmd-ts/dist/cjs/argparser.js").ParsingResult<{
    command: "status";
    value: Promise<void>;
  } | {
    command: "database";
    value: {
      command: "list";
      value: Promise<void>;
    };
  } | {
    command: "template";
    value: {
      command: "list";
      value: Promise<void>;
    } | {
      command: "show";
      value: Promise<void>;
    };
  } | {
    command: "schema";
    value: {
      command: "show";
      value: Promise<void>;
    } | {
      command: "export";
      value: Promise<void>;
    } | {
      command: "ddl";
      value: Promise<void>;
    } | {
      command: "instantiate";
      value: Promise<void>;
    };
  } | {
    command: "table";
    value: {
      command: "list";
      value: Promise<void>;
    } | {
      command: "show";
      value: Promise<void>;
    } | {
      command: "create";
      value: Promise<void>;
    } | {
      command: "alter";
      value: Promise<void>;
    } | {
      command: "drop";
      value: Promise<void>;
    };
  } | {
    command: "row";
    value: {
      command: "list";
      value: Promise<void>;
    } | {
      command: "add";
      value: Promise<void>;
    } | {
      command: "get";
      value: Promise<void>;
    } | {
      command: "update";
      value: Promise<void>;
    } | {
      command: "delete";
      value: Promise<void>;
    } | {
      command: "upsert";
      value: Promise<void>;
    };
  } | {
    command: "sql";
    value: Promise<void>;
  }>>;
};
// #endregion